# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml
# see also https://www.appveyor.com/docs/windows-images-software/#python

image: Visual Studio 2019

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python39"

matrix:
  fast_finish: false

init:
  - "python -V"

install:
  - "python -m pip install -r maintenance/requirements.txt"

test_script:
  - "python maintenance/github-crawler.py"
